### ISSUE TITLE
Saving Multilingual Embeddings

### ISSUE THREAD

**Issue by yigitsever** [anoopkunchukuttan/geomm#3]
Hello,  geomm.py includes a snippet to save embeddings (prepended with  ### Save the GeoMM embeddings if requested), how would one go to save multilingual embeddings in geomm_multi.py?

**Comment by pratikjawanpuria** [comment]
Hi @yigitsever, we are currently occupied with some internal deadlines. We will get back on this next week. Hope this is fine.

**Comment by arjunbalgovind** [comment]
Hi @yigitsever, we have added the model and embedding save functionality to geomm_multi.py as well. You can use the arguments --model_path and --geomm_embeddings_path to save them. Since the language names aren't known in the code, the saved embeddings will be named based on their language indexing as provided in the input.

**Comment by anoopkunchukuttan** [comment]
Feature implemented, hence closing
